# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 600)
        self.settings_frame = QtWidgets.QFrame(Form)
        self.settings_frame.setGeometry(QtCore.QRect(0, 0, 600, 150))
        self.settings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_frame.setObjectName("settings_frame")
        self.file_path = QtWidgets.QLineEdit(self.settings_frame)
        self.file_path.setGeometry(QtCore.QRect(50, 40, 400, 25))
        self.file_path.setObjectName("file_path")
        self.browse_label = QtWidgets.QLabel(self.settings_frame)
        self.browse_label.setGeometry(QtCore.QRect(50, 10, 200, 20))
        self.browse_label.setObjectName("browse_label")
        self.browse_btn = QtWidgets.QPushButton(self.settings_frame)
        self.browse_btn.setGeometry(QtCore.QRect(480, 40, 100, 25))
        self.browse_btn.setObjectName("browse_btn")
        self.rotate_btn = QtWidgets.QPushButton(self.settings_frame)
        self.rotate_btn.setGeometry(QtCore.QRect(50, 80, 100, 23))
        self.rotate_btn.setObjectName("rotate_btn")
        self.filter1_btn = QtWidgets.QPushButton(self.settings_frame)
        self.filter1_btn.setGeometry(QtCore.QRect(50, 120, 100, 23))
        self.filter1_btn.setObjectName("filter1_btn")
        self.flipupdown_btn = QtWidgets.QPushButton(self.settings_frame)
        self.flipupdown_btn.setGeometry(QtCore.QRect(200, 80, 100, 23))
        self.flipupdown_btn.setObjectName("flipupdown_btn")
        self.filter2_btn = QtWidgets.QPushButton(self.settings_frame)
        self.filter2_btn.setGeometry(QtCore.QRect(200, 120, 100, 23))
        self.filter2_btn.setObjectName("filter2_btn")
        self.flipleftright_btn = QtWidgets.QPushButton(self.settings_frame)
        self.flipleftright_btn.setGeometry(QtCore.QRect(350, 80, 100, 23))
        self.flipleftright_btn.setObjectName("flipleftright_btn")
        self.filter3_btn = QtWidgets.QPushButton(self.settings_frame)
        self.filter3_btn.setGeometry(QtCore.QRect(350, 120, 100, 23))
        self.filter3_btn.setObjectName("filter3_btn")
        self.save_btn = QtWidgets.QPushButton(self.settings_frame)
        self.save_btn.setGeometry(QtCore.QRect(480, 80, 100, 23))
        self.save_btn.setObjectName("save_btn")
        self.close_btn = QtWidgets.QPushButton(self.settings_frame)
        self.close_btn.setGeometry(QtCore.QRect(480, 120, 100, 23))
        self.close_btn.setObjectName("close_btn")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 159, 581, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.browse_label.setText(_translate("Form", "Browse a path for image"))
        self.browse_btn.setText(_translate("Form", "browse"))
        self.rotate_btn.setText(_translate("Form", "rotate"))
        self.filter1_btn.setText(_translate("Form", "filter-1"))
        self.flipupdown_btn.setText(_translate("Form", "flip up-down"))
        self.filter2_btn.setText(_translate("Form", "filter-2"))
        self.flipleftright_btn.setText(_translate("Form", "flip left-right"))
        self.filter3_btn.setText(_translate("Form", "filter-3"))
        self.save_btn.setText(_translate("Form", "save"))
        self.close_btn.setText(_translate("Form", "close"))
